name: ctdcal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - click=8.0.1
  - gsw
  - matplotlib==3.4.3
  - numpy<1.23
  - pandas==1.3.3
  - PyYAML==5.4.1
  - requests
  - scipy==1.7.0
  - Sphinx==4.2.0
  - jupyter==1.0.0
  - furo==2021.9.8
  - nbsphinx==0.8.7
  - jupytext==1.12.0
  - black
  - flake8
  - isort
  - pre-commit
  - pytest
  - bokeh
  - mypy
  - pytest-cov
  - munch
